=== Linofff/studia/dtdszyme/file.dtd
<!ENTITY % visual "(image | gif)">
<!ENTITY % difficultyType "(easy | easy+ | medium | medium+ | hard | hard+)">
<!ENTITY % levelType "(beginner | intermediate | advanced | all)">
<!ENTITY % linkType "(youtube_channel | youtube_video | simple_website)">
<!ENTITY % resourceAttr1 "src CDATA #REQUIRED">
<!ENTITY % resourceAttr2 "caption CDATA #IMPLIED">


<!ELEMENT project (introduction, tutorials, recommendations)>
<!ATTLIST project 
	creator CDATA "anonymous" 
	about CDATA #REQUIRED>

<!ELEMENT introduction (definition*, goal)>
<!ELEMENT definition (term, meaning)>
<!ELEMENT goal (#PCDATA)>
<!ELEMENT term (#PCDATA)>
<!ELEMENT meaning (#PCDATA)>

<!ELEMENT tutorials (tutorial+, external?)>
<!ELEMENT tutorial (name, description+, steps, additional?)>
<!ATTLIST tutorial 
	difficulty %difficultyType; #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description 
	type (introduction | presentation) #REQUIRED>

<!ELEMENT steps (step+)>
<!ELEMENT step (instructions, sidenote?)>
<!ATTLIST step 
	n CDATA #REQUIRED>

<!ELEMENT instructions (#PCDATA | %visual;)*>

<!ELEMENT image EMPTY>
<!ATTLIST image 
	%resourceAttr1;
	%resourceAttr2;>

<!ELEMENT gif EMPTY>
<!ATTLIST gif 
	%resourceAttr1;
	%resourceAttr2;>

<!ELEMENT external (source+)>
<!ELEMENT source (name, link, description, rating)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link 
	format %linkType; #REQUIRED>

<!ELEMENT rating (#PCDATA)>

<!ELEMENT additional ((%visual;)*, credit?)>
<!ELEMENT credit (#PCDATA | link)*>

<!ELEMENT recommendations (recommendation+)>
<!ELEMENT recommendation (#PCDATA | link | %visual;)*>
<!ATTLIST recommendation 
	level %levelType; #IMPLIED>

=== Linofff/studia/dtdszyme/file.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE project SYSTEM "./file.dtd">
<project creator="Szymon Pecka" about="card tricks">
  <introduction>
    <definition>
      <term>Card Trick</term>
      <meaning>Any sleight of hand that can be done with cards (anything from magic tricks to
        cardistry)</meaning>
    </definition>
    <goal>To encourage others to learn and practice card tricks</goal>
  </introduction>
  <tutorials>
    <tutorial difficulty="easy">
      <name>21 Cards</name>
      <description type="presentation">The spectator chooses one of 21 standard, randomly picked,
        shuffled cards, they are then dealt out face up in 3 columns of 7 cards, the spectator
        points to the column with his card for the magician, the cards get picked up and the process
        is repeated 2 more times. At the end the magician reveals the card selected by the
        spectator.</description>
      <description type="introduction">It actually doesn't involve any sleight of hand, it's based
        on math.</description>
      <steps>
        <step n="1">
          <instructions>
            Prepare a pile of 21 standard playing cards
          </instructions>
        </step>
        <step n="2">
          <instructions>
            Let the spectator choose one of 21 cards, tell them to carefully memorize it
          </instructions>
        </step>
        <step n="3">
          <instructions>
            Shuffle the cards and lay them out in 3 columns of 7 cards (row by row)
          </instructions>
        </step>
        <step n="4">
          <instructions>
            Ask the spectator to point to the column where his card is
          </instructions>
        </step>
        <step n="5">
          <instructions>
            Pick up the cards, put the pile with the spectator's card in the middle, between the
            other 2 packets
          </instructions>
        </step>
        <step n="6">
          <instructions>
            Repeat the last 3 steps 2 more times
          </instructions>
        </step>
        <step n="7">
          <instructions>
            The spectator's card will now be in the 11th position from the top
          </instructions>
        </step>
      </steps>
      <additional>
        <gif src="resources\images\21cards-animation.gif"
          caption="An animation to help visualize how the trick works" />
        <credit>The GIF was sourced from <link format="simple_website">
          https://en.wikipedia.org/wiki/Twenty-One_Card_Trick</link></credit>
      </additional>
    </tutorial>

    <tutorial difficulty="easy+">
      <name>Reversed Card</name>
      <description type="presentation">The spectator picks a random card from a standard deck of
        cards, memorizes it, then puts it back. The magician snaps his fingers and spreads out the
        cards, the card picked by the spectator is the only one facing the other way, it has been
        "magically" reversed.</description>
      <description type="introduction">It all bases off of a simple idea and clever misdirection.</description>
      <steps>
        <step n="1">
          <instructions> Take the card at the bottom of the deck and flip it. <visual>
              <image src="/resources/images/t-1.png" />
              <image src="/resources/images/t-2.png" />
              <image src="/resources/images/t-3.png" />
              <image src="/resources/images/t-4.png" />
            </visual>
          </instructions>
          <sidenote>This is usually done before approaching the spectator, but if you're clever with
            your misdirection you can do it directly in front of them.</sidenote>
        </step>
        <step n="2">
          <instructions> Let the spectator choose their card, be careful not to show the last one. <visual>
              <image src="/resources/images/t-5.png" />
            </visual>
          </instructions>
        </step>
        <step n="3">
          <instructions> While the spectator is trying to memorize their card sneakily flip the
            deck. Thanks to the card we flipped before it won't look any different, but in actuality
            all of the cards except the top one will now be face up. <visual>
              <image src="/resources/images/t-6.png" />
              <image src="/resources/images/t-7.png" />
            </visual>
          </instructions>
        </step>
        <step n="4">
          <instructions> Take the card from the spectator and put it back somewhere in the middle of
            the deck, be careful not to let the cards spread out. <visual>
              <image src="/resources/images/t-8.png" />
              <image src="/resources/images/t-9.png" />
            </visual>
          </instructions>
        </step>
        <step n="5">
          <instructions> You have to bring the attention of the spectator somewhere else (chatting
            them up, recounting what happend so far in the trick, talking in some shape or form
            usually does the trick) and sneakily flip the deck once again. If you can manage it you
            should also flip the bottom card once again to return to it to it's normal orientation. <visual>
              <image src="/resources/images/t-10.png" />
              <image src="/resources/images/t-11.png" />
            </visual>
          </instructions>
          <sidenote>For a beginner this might be the hardest part</sidenote>
        </step>
        <step n="6">
          <instructions>
            Build some tension: snap your fingers, wave your hand, at this point as long as you
            flipped the bottom card you can even give the deck back to the spectator.
          </instructions>
        </step>
        <step n="7">
          <instructions> At long last spread the cards out and reveal that one card has been
            "magically" fliped and that it is precisely the spectator's card. <visual>
              <image src="/resources/images/t-12.png" />
              <image src="/resources/images/t-13.png" />
            </visual>
          </instructions>
        </step>
      </steps>
      <additional>
        <credit>The images were sourced from <link format="youtube_channel">
          https://www.youtube.com/@TheMagicChannelCardTricks</link></credit>
      </additional>
    </tutorial>

    <external>
      <source>
        <name>A million card tricks</name>
        <link format="youtube_channel">https://www.youtube.com/@AMillionCardTricks</link>
        <description>A youtube channel dedicated to teaching magic tricks, a guide through all the
          mastery levels, you'll find something interesting to learn no matter if you're a beginner,
          intermediate or advanced magician</description>
        <rating>9/10</rating>
      </source>
      <source>
        <name>lotusinhand</name>
        <link format="youtube_channel">https://www.youtube.com/@lotusinhand</link>
        <description>A youtube channel dedicatd to teaching exclusively cardistry, well made
          tutorials on a lot of moves, but not that many videos</description>
        <rating>8</rating>
      </source>
    </external>
  </tutorials>
  <recommendations>
    <recommendation level="beginner">
      Simply pick up any deck of cards and start practicing, that's the beauty of it, if you have a
      deck of cards (even simple, paper ones) in your household you can see if it's something you
      like even right now.
    </recommendation>
    <recommendation level="beginner intermediate"> Once you get a feel for things, and have invested
      some time into it and concluded that it's something you enjoy, consider investing into a
      Bicycle Deck, they are great no matter the level of mastery of card tricks. You can find them
      virtually in any shop that sells things like these, but here is an example link <link
        format="simple_website">
      https://www.empik.com/bicycle-standard-back-red-karty-klasyczne-rewers-czerwony-u-s-playing-card-company,p1374794845,zabawki-p</link>
			<image
        src="/resources/images/bicycle-classic-red-reverse_upscale.jpg"
        caption="This is how a standard Bicycle Deck looks like" />
    </recommendation>
    <recommendation level="all">
      Never do the same trick twice for the same person. (Rules exist to be broken of course, but do
      it only if you're really sure you can get away with it, it'll save you a lot of headaches).
    </recommendation>
  </recommendations>
</project>
